[build]
# custom build command that install bun and run build
command = "bun --bun run build"
# vite output folder
publish = "dist"

[build.environment]
# disable NPM install
NPM_FLAGS = "--version"
